version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app/web
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
  backend:
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app/backend
    command: npm run start:dev
